### ISSUE TITLE
Showing image from post as Thumbnail

### ISSUE THREAD

**Issue by MeowCold** [raivis-vitols/ghost-theme-willow#1]
How is it Showing image from post as Thumbnail？

**Comment by raivis-vitols** [comment]
@MeowCold, hi! Sorry, can you explain / ellaborate, please?

**Comment by MeowCold** [comment]
hi
Thank you for your answer to my question
How to use the article as the first picture Home thumbnails and add at the end of the pre-command -Thumbnail
similar
https://xxxx.com/sample1.jpg-Thumbnail

**Comment by MeowCold** [comment]
http://dl.ybyys.com/blog/image/2015/04/LeTV-LeMe-logo.jpg
http://dl.ybyys.com/blog/image/2015/04/LeTV-LeMe-logo.jpg-Thumbnail

**Comment by raivis-vitols** [comment]
Unfortunately, I do not know how to achieve that. I am simply using the default Ghost's featured image upload and display image in tiles as it is.

**Comment by Rubel-hossain** [comment]
{{#foreach posts}}

 ` <img src="{{image}}" alt="blog">`

{{/foreach}}
