### ISSUE TITLE
Post Image Sizes

### ISSUE THREAD

**Issue by jdchandler** [raivis-vitols/ghost-theme-willow#12]
I seen that all of your Post Image sizes are the same which is why it lines up pretty perfect. Is there a way you could make it so regardless of the picture size, make the picture fit some "fixed" size, and have the rows of post be lined up evenly?

TLDR - Is there a way to keep all posts aligned while not having to worry about post image sizes before hand?

**Comment by raivis-vitols** [comment]
Hi, @jdchandler!

Yeah, I understand what you mean. I think following approach could help you:

1) Update post list template - remove` <img>` element from .c-post-list__image link;
2) Update .c-post-list__image link - add style attribute that sets it's background to post image. Like this:

```
<a class="c-post-list__image" href="{{url}}" title="{{title}}" style="background:url({{image}})"></a>
```

3) Update SASS / CSS for .c-post-list__image element, set padding-bottom to 50%, background-position to 50% 50% and background-size to cover.

Just tried this in browser, worked well for me. I hope I did not forget anything. Anyway, this should be a good starting point for you to get it working! Best of luck!
